### ISSUE TITLE
Percy Analysis Extension - Reporting doesn't work when the build is failed and no snapshots are uploaded in Percy

### ISSUE THREAD

**Issue by sadeesh-sdet** [test-results-reporter/reporter#113]
Considering the use-case that a percy's visual test is failed even at functional step(ex: elements' locator change) before executing the visual tests and because of this, the build/test will fail and the same will be captured like below in Percy

![image](https://user-images.githubusercontent.com/87024075/212061394-20fee5f2-892c-492d-832e-3efd14cafd95.png)

In this case, the reporter plugin doesn't notify the results and its execution doesn't stop. Guess, it keeps on retry [here](https://github.com/test-results-reporter/reporter/blob/86abe18b9124ffb8c36525f27c09cd18d650b5c8/src/extensions/percy-analysis.js#L71).

**Comment by sadeesh-sdet** [comment]
![image](https://user-images.githubusercontent.com/87024075/212094552-387286a4-906e-44fa-b910-44349182390e.png)
I see, the state for this case is "failed". Please check [this reference] from percy (https://github.com/percy/cli/blob/d5e21c4b38dda48e4bdc15240bd5ae1376bfb2c6/packages/cli-build/src/wait.js#L94)

**Comment by ASaiAnudeep** [comment]
do you want to raise a PR with a fix?

**Comment by sadeesh-sdet** [comment]
@ASaiAnudeep Many thanks for this kind opportunity. Let me give it a try and test this by including the "failed" case in [this condition](https://github.com/test-results-reporter/reporter/blob/86abe18b9124ffb8c36525f27c09cd18d650b5c8/src/extensions/percy-analysis.js#L73) step and a regression around it.

**Comment by sadeesh-sdet** [comment]
@ASaiAnudeep  Please review [this pull request](https://github.com/test-results-reporter/reporter/pull/115) as it has been addressed and resolved this observation.
