### ISSUE TITLE
Not getting test summary report on Google Chat

### ISSUE THREAD

**Issue by akshaygadekar3** [test-results-reporter/reporter#130]
I am using `cypress-mochawesome-reporter` to generate test reports in JSON.

I am receiving the reports in `test-summary-slim` format only. I have tried configuring `publish:test-summary` but still the results are the same.

**Comment by ASaiAnudeep** [comment]
Hello @akshaygadekar3 , could you please share your config and result files with us.

**Comment by akshaygadekar3** [comment]
Hello @ASaiAnudeep, 

Kindly browse https://github.com/akshaygadekar3/cypress_example

the config file is at: https://github.com/akshaygadekar3/cypress_example/blob/master/cypress.config.js
the result file is at: https://github.com/akshaygadekar3/cypress_example/blob/master/cypress/reports/html/index.json
the report screenshot on Gchat: https://github.com/akshaygadekar3/cypress_example/blob/master/screenshots/Screenshot%20from%202023-05-27%2017-15-44.png

Let me know if you need anything from my end.
Looking forward to your response.

**Comment by ASaiAnudeep** [comment]
This might be related to - https://github.com/test-results-reporter/reporter/issues/133 which was fixed in https://github.com/test-results-reporter/parser/releases/tag/v0.1.5

Please reopen, if not resloved.
