### ISSUE TITLE
It doesn't calculate the suite's tests when it has the context between the its (test)

### ISSUE THREAD

**Issue by joel-antonio** [test-results-reporter/reporter#133]
Guys, I'm facing a problem of the following nature: my automated tests in cypress, we organize the tests in describe, context. The its inside contexts are not calculated in the report in the test suites, only in the main calculation. Is there any way or any documentation that it would be possible to calculate?
The image shows that the first test suite which has describe and context with value 0 of tests. the second test suite that has only describe the correct calculation as expected.

![image](https://github.com/test-results-reporter/reporter/assets/135665093/abf7a881-9acc-4e09-b236-b40bec18aa03)

**Comment by ASaiAnudeep** [comment]
Thank you for reaching out. To better assist you, could you please check the results file and share both the configuration file and the results file? This will help us take a closer look at the setup and results to provide more specific guidance.

**Comment by joel-antonio** [comment]
@ASaiAnudeep Do you need any more information?
