### ISSUE TITLE
[Help] parallelize report in slack

### ISSUE THREAD

**Issue by MarcosPereira1** [test-results-reporter/reporter#137]
I want to parallelize the execution of tests in GitHub Actions using Cypress and Report Tests, and according to the parallel execution, report each test group in a different Slack channel. For example, I will run tests from 4 different teams simultaneously, and these tests will be executed in parallel. Therefore, each test group will run in parallel. My question is whether I can perform this process of sending the report to different channels in Slack.

**Comment by ASaiAnudeep** [comment]
Unfortunately, the current configuration of our tool doesn't support the specific requirement of reporting each test group to different Slack channels. Thanks for your interest and feedback. We'll certainly consider it for future updates.
