### ISSUE TITLE
the .json file generated by the cypress-mochawesome-reporter" version: "^3.7.0" does not bring the summary report in slack even when inserting the "publish": "test-summary" attribute

### ISSUE THREAD

**Issue by joel-antonio** [test-results-reporter/reporter#143]
the .json file generated by the cypress-mochawesome-reporter" version: "^3.7.0" does not bring the summary report in slack even when inserting the "publish": "test-summary" attribute
Current version:
[index_bot.json](https://github.com/test-results-reporter/reporter/files/13774596/index_bot.json)
![image](https://github.com/test-results-reporter/reporter/assets/135665093/dcc7e94e-b895-45a6-b4a0-776b7862973f)

Old version:
[index_bot.json](https://github.com/test-results-reporter/reporter/files/13774675/index_bot.json)
![image](https://github.com/test-results-reporter/reporter/assets/135665093/e0fe40fa-65ac-4ba4-ab27-c6d975ddbfd0)

I noticed that with this generated version of the json it is a little different from the previous one.

**Comment by ASaiAnudeep** [comment]
Hello @joel-antonio, could you please point out the specific changes you've observed in the output result JSON file that could potentially affect the result summary? I don't see much differences in the shared result files.
