### ISSUE TITLE
Test suite limit optimization

### ISSUE THREAD

**Issue by KosalaiV** [test-results-reporter/reporter#151]
Hi @ASaiAnudeep Thanks for making a progress here. Could we enhance this to accommodate more than 10 test suites? If so, this plugin would truly shine.

Thank You!

_Originally posted by @KosalaiV in https://github.com/test-results-reporter/reporter/issues/144#issuecomment-1975797183_

**Comment by ASaiAnudeep** [comment]
@KosalaiV  , I've added a new input called max_suites, which is set to a default value of 10, allowing you to adjust the limit on the number of suites.
```json
{
  "name": "slack",
  "inputs": {
    "url": "<slack-incoming-webhook-url>",
    "max_suites": 20
  }
}
```

I will update the docs in sometime.
