### ISSUE TITLE
Conditional hyperlinks

### ISSUE THREAD

**Issue by ASaiAnudeep** [test-results-reporter/reporter#7]
hyperlinks should support an additional optional field called `condition` to determine whether to attach the given hyperlink to the teams or slack message.

**Condition could be**
- pass
- fail
- passOrFail (default)

### Example

```json
{ 
  "name": "hyperlinks", 
  "inputs": { 
    "links": [ 
      { 
        "text": "Build Logs", 
        "url": "<build-logs-url>",
        "condition": "fail"
      }
    ] 
  }
}  
```

### Use Case

- Attach a application logs hyperlink when test cases have failed.

**Comment by leelaprasadv** [comment]
@ASaiAnudeep I'll take this up
